#!/bin/bash

# 1. GLOBAL VARIABLES
# echo "${@:1:${#}-1}" : GETTING ALL BEFORE LAST
# THE PATTERN SHOULD BE THE LAST ARGUMENT
PATTERN="${@: -1}"

# THE CURRENT DIRECTORY
DIRECT=.

# DIRECTORY CONTAINING THE SCRIPT
ROOTDIR=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# THE PARENT DIRECTORY OF CURRENT DIRECTORY
UP=$(builtin cd $ROOTDIR; builtin cd ..;  pwd)

# DEFAULT ARGUMENTS TO THE COMMAND
OPTIONS=("-REn" "--color")

# CURRENT SCRIPT NAME
SCRIPTNAME=$(basename $0)

# 2. FUNCTIONS
# USAGE FUNCTION
usage() {
    echo "Usage: $SCRIPTNAME [options] <egrep-pattern>"
    echo "Search patterns recursively in a directory files"
    
    echo "Options can be one or more of:"
    echo "use -h, --help for getting help"
    exit $1
}

# ERROR FUNCTION
errorMessage() {
    echo "$SCRIPTNAME: $1"
    exit 1
}

# 3. PROCESS OPTIONS
# IF ARGUMENTS ARE NOT SPECIFIED
[ $# -eq 0 ] && usage 1

# IF ONE ARG
if [ $# -eq 1 ] ; then
    OPTIONS+=("--include=*.c --include=*.h --include=*.hpp --include=*.cpp")

else
    # IF MORE THAN 1 ARGS - THE LAST ARG BE THE PATTERN - DO NOT SHIFT IT
    while [ $# -ge 2 ] ; do

        case "$1" in

            # PRINT HELP (USAGE) MESSAGE
            -h | --help) usage 0
                ;;

            # SEARCHING THROUGH ALL FILES, NOT JUST C, CPP
            --all) break
                ;;

            # SEARCHING THROUGH TEXT FILES
            --text) OPTIONS+=("--include=*.txt --include=*texi --include=*md --include=README.*")
                ;;

            # SEARCHING THROUGH C AND CPP FILES
            --c) OPTIONS+=("--include=*.c --include=*.h --include=*.hpp --include=*.cpp")
                ;;

            # SEARCHING THROUGH PYTHON FILES
            --py) OPTIONS+=("--include=*.py --include=*json --include=*xml")
                ;;

            # CASE INSENSITIVE SEARCH
            -i | --insensitive) OPTIONS+=("-i")
                ;;
                
            # SEARCH FROM SPECIFIED DIRECTORY - to be worked on
            --top=*)
                # SPECIFY ANYTHING NEXT TO --top 
                DIRECT="${1##*=}" 
                OPTIONS+=("--include=*.c --include=*.h --include=*.hpp --include=*.cpp")
                ;;

            --top)
                # SPECIFY ANYTHING NEXT TO --top 
                OPTIONS+=("--include=*.c --include=*.h --include=*.hpp --include=*.cpp")
                DIRECT="${2}"
                ;;

            # SEARCH FROM PARENT DIRECTORY
            --up) DIRECT=$PARENT
                ;;

            # WHEN THE SPECIFIED OPTION IS NOT AVALIABLE
            -*) errorMessage "Invalid option $1"
                ;;

            # DEFAULT CASE
            *) break
                ;;
            
        esac

        # SHIFT TO THE NEXT (ARG) OPTION
        shift
    done
fi

# 4 BODY - PERFORMING THE SEARCHING
grep -REn --color ${OPTIONS[@]} "$PATTERN" "$DIRECT"